version: "3.8"

services:
  app:
    build:
      target: ${BUILD_TARGET:-dev}
      args:
        DEVELOPER_UID: ${DEVELOPER_UID:-1000}
    image: go-dummy-http-${BUILD_TARGET:-dev}:latest
    restart: on-failure
    working_dir: /go/src/app
    ports:
      - "80:80"
    volumes:
      - ./:/go/src/app
      - gopkg:/go/pkg/
      - gobin:/go/bin/
    networks:
      net:
    tty: true

volumes:
  gopkg:
    name: gopkg
  gobin:
    name: gobin

networks:
  net:
    name: developer
