version: "3.8"

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    user: ${DEVELOPER_UID}
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: ${BUILD_TARGET}
      args:
        - DEVELOPER_UID
    restart: on-failure
    working_dir: /go/src/app
    ports:
      - "80:80"
    volumes:
      - ../:/go/src/app
      - gopkg:/go/pkg/
      - gobin:/go/bin/
    networks:
      application:
    tty: true

volumes:
  gopkg:
    name: ${COMPOSE_PROJECT_NAME}_gopkg
  gobin:
    name: ${COMPOSE_PROJECT_NAME}_gobin

networks:
  application:
    name: ${COMPOSE_PROJECT_NAME}_network
